use_default_settings: true

general:
  instance_name: "Daily Stock Analysis Search"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  secret_key: "$SEARXNG_SECRET"
  public_instance: false
  limiter: false
  image_proxy: false
